apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:persistenceagent-1.0.2
        imagePullPolicy: IfNotPresent
      serviceAccountName: ml-pipeline-persistenceagent
