apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-ui
  name: ml-pipeline-ui
spec:
  selector:
    matchLabels:
      app: ml-pipeline-ui
  template:
    metadata:
      labels:
        app: ml-pipeline-ui
    spec:
      containers:
      - name: ml-pipeline-ui
        image: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:frontend-1.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: ALLOW_CUSTOM_VISUALIZATIONS
          value: "true"
        ports:
        - containerPort: 3000
      serviceAccountName: ml-pipeline-ui
